# Generated by Django 4.2 on 2025-11-25 12:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tinder', '0002_alter_tinder_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('desciptions', models.TextField(max_length=1500)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('INPROGRESS', 'INPROGRESS'), ('COMPLETED', 'COMPLETED')], default='NEW', max_length=75)),
                ('code', models.CharField(blank=True, choices=[('NEW', 'NEW'), ('INPROGRESS', 'INPROGRESS'), ('COMPLETED', 'COMPLETED')], max_length=120, null=True)),
                ('begin_project', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_user', to=settings.AUTH_USER_MODEL)),
                ('tinder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tender_project', to='tinder.tinder')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('unit', models.CharField(default='pice', max_length=75)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='myproject.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(max_length=1500)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2025, 11, 25, 12, 37, 4, 137898, tzinfo=datetime.timezone.utc))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actiom_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_project', to='myproject.project')),
            ],
        ),
    ]
