# Generated by Django 4.2 on 2025-11-26 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectaction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 26, 7, 24, 37, 528520, tzinfo=datetime.timezone.utc)),
        ),
    ]
