# Generated by Django 4.2 on 2025-11-26 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_alter_projectaction_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectaction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 26, 12, 33, 37, 533812, tzinfo=datetime.timezone.utc)),
        ),
    ]
