# Generated by Django 4.2 on 2025-11-26 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_alter_projectaction_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectaction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 26, 13, 7, 39, 341827, tzinfo=datetime.timezone.utc)),
        ),
    ]
