# Generated by Django 4.2 on 2025-11-27 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_alter_projectaction_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='item',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectaction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 27, 7, 0, 4, 379608, tzinfo=datetime.timezone.utc)),
        ),
    ]
