# Generated by Django 4.2 on 2025-11-27 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_projectitem_item_alter_projectaction_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='projectaction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 27, 7, 2, 14, 627140, tzinfo=datetime.timezone.utc)),
        ),
    ]
