# Generated by Django 4.2 on 2025-11-27 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0008_projectitem_statment_alter_projectaction_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 11, 27, 9, 50, 12, 79327, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, choices=[('NEW', 'جديد'), ('INPROGRESS', 'مازال مستمر'), ('COMPLETED', 'تم الانتهاء')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('NEW', 'جديد'), ('INPROGRESS', 'مازال مستمر'), ('COMPLETED', 'تم الانتهاء')], default='NEW', max_length=75),
        ),
        migrations.AlterField(
            model_name='projectaction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 27, 9, 50, 12, 79327, tzinfo=datetime.timezone.utc)),
        ),
    ]
