# Generated by Django 4.2 on 2025-11-29 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0010_alter_project_code_alter_project_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 11, 29, 8, 0, 23, 584147, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='projectaction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 29, 8, 0, 23, 591247, tzinfo=datetime.timezone.utc)),
        ),
    ]
