# Generated by Django 4.2 on 2025-11-30 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0013_alter_project_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 11, 30, 10, 50, 24, 476221, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='projectaction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 10, 50, 24, 477252, tzinfo=datetime.timezone.utc)),
        ),
    ]
