# Generated by Django 4.2 on 2025-12-02 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0019_alter_project_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 12, 2, 7, 10, 2, 82877, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='projectaction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 2, 7, 10, 2, 82877, tzinfo=datetime.timezone.utc)),
        ),
    ]
