# Generated by Django 4.2 on 2025-11-10 12:08

import contact.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Company_by',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=75, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=25, validators=[contact.models.validate_number])),
                ('tax_file', models.FileField(upload_to='tax_file')),
                ('notes', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=75, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=25, validators=[contact.models.validate_number])),
                ('balance', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], max_length=120)),
                ('notes', models.CharField(max_length=1500)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_category', to='contact.category')),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=75, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=25, validators=[contact.models.validate_number])),
                ('notes', models.CharField(max_length=1500)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Competitor_category', to='contact.category')),
            ],
        ),
        migrations.AddIndex(
            model_name='company_by',
            index=models.Index(fields=['code'], name='contact_com_code_b595cc_idx'),
        ),
        migrations.AddIndex(
            model_name='company_by',
            index=models.Index(fields=['name'], name='contact_com_name_ae4af3_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['code'], name='contact_sup_code_368466_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name', 'category'], name='contact_sup_name_d51f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['code'], name='contact_com_code_0319dd_idx'),
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['name', 'category'], name='contact_com_name_5165c7_idx'),
        ),
    ]
