# Generated by Django 4.2 on 2025-11-23 10:50

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=75, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=25, validators=[contact.models.validate_number])),
                ('balance', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], max_length=120)),
                ('notes', models.CharField(max_length=1500)),
            ],
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['code'], name='contact_cus_code_42abb4_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='contact_cus_name_590a44_idx'),
        ),
    ]
