# Generated by Django 4.2 on 2025-11-04 14:13

from django.db import migrations, models
import utils.generate_code


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=utils.generate_code.generate_code, max_length=75)),
                ('name', models.CharField(max_length=120)),
                ('notes', models.TextField(max_length=1500)),
            ],
        ),
    ]
