# Generated by Django 4.2 on 2025-11-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_product_price_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
