# Generated by Django 4.2 on 2025-11-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainitem',
            name='code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
