# Generated by Django 4.2 on 2025-11-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_mainitem_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='code_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='code_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
