# Generated by Django 4.2 on 2025-11-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_brand_code_no_product_code_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='code_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
