# Generated by Django 4.2 on 2025-11-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_brand_code_no_alter_product_code_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='code',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
