# Generated by Django 4.2 on 2025-11-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_brand_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainitem',
            name='code_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainitem',
            name='code',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
