# Generated by Django 4.2 on 2025-12-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_mainitem_code_no_alter_mainitem_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='code_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
