# Generated by Django 4.2 on 2025-12-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_store_code_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transation_no',
            new_name='reset_no',
        ),
        migrations.AddField(
            model_name='transaction',
            name='avg_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='in_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='out_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
