# Generated by Django 4.2 on 2025-12-07 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_rename_transation_no_transaction_reset_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='avg_price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='in_no',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='out_no',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='quantity',
        ),
        migrations.CreateModel(
            name='TranSItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('avg_price', models.FloatField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_product', to='inventory.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_transactions', to='inventory.transaction')),
            ],
        ),
    ]
