# Generated by Django 4.2 on 2025-11-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='photo_user/0.jpg', null=True, upload_to='photo_user'),
        ),
    ]
