# Generated by Django 4.2 on 2025-11-25 12:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinder.models
import utils.generate_code


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=utils.generate_code.generate_code, max_length=75)),
                ('title', models.CharField(max_length=120)),
                ('descriptions', models.TextField(max_length=1500)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('CANCEL', 'CANCEL'), ('AWARED', 'AWARED')], max_length=75)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 11, 25, 12, 22, 7, 869758, tzinfo=datetime.timezone.utc))),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('insurance_amount', models.FloatField()),
                ('insurance_type', models.CharField(choices=[('CASH', 'CASH'), ('CHEQUE', 'CHEQUE'), ('BANK_GUARANTEE', 'BANK_GUARANTEE')], max_length=120)),
                ('offer_value', models.FloatField()),
                ('awared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tinder_supplier', to='contact.competitor')),
                ('company_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tinder_supplier', to='contact.company_by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tinder_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TindetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=120)),
                ('quantity', models.FloatField()),
                ('code', models.CharField(blank=True, max_length=25, null=True)),
                ('supply_price', models.FloatField(blank=True, null=True)),
                ('tinder_price', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(default='pice', max_length=25)),
                ('tinder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_tinder', to='tinder.tinder')),
            ],
        ),
        migrations.CreateModel(
            name='TinderFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to=tinder.models.tender_file_upload_path)),
                ('title', models.CharField(max_length=120)),
                ('tinder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filestinder', to='tinder.tinder')),
            ],
        ),
        migrations.AddIndex(
            model_name='tinder',
            index=models.Index(fields=['code'], name='tinder_tind_code_f0bf54_idx'),
        ),
        migrations.AddIndex(
            model_name='tinder',
            index=models.Index(fields=['status'], name='tinder_tind_status_41d395_idx'),
        ),
    ]
