# Generated by Django 4.2 on 2025-11-25 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 25, 12, 37, 4, 137898, tzinfo=datetime.timezone.utc)),
        ),
    ]
