# Generated by Django 4.2 on 2025-11-26 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0002_alter_tinder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tindetitem',
            name='statement',
            field=models.TextField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tinder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 26, 7, 24, 37, 518635, tzinfo=datetime.timezone.utc)),
        ),
    ]
