# Generated by Django 4.2 on 2025-11-11 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0003_alter_tinder_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinder',
            name='file',
        ),
        migrations.AlterField(
            model_name='tinder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 11, 12, 21, 31, 435622, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tinder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('CANCEL', 'cancel'), ('AWARED', 'AWARED')], max_length=75),
        ),
    ]
