# Generated by Django 4.2 on 2025-11-26 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0003_tindetitem_statement_alter_tinder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 26, 12, 33, 37, 520784, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tindetitem',
            name='supply_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tindetitem',
            name='tinder_price',
            field=models.FloatField(default=0),
        ),
    ]
