# Generated by Django 4.2 on 2025-11-12 07:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tinder', '0004_remove_tinder_file_alter_tinder_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 12, 7, 49, 39, 246935, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tinder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tinder_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
