# Generated by Django 4.2 on 2025-11-26 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0004_alter_tinder_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 26, 13, 7, 39, 335266, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tindetitem',
            name='supply_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tindetitem',
            name='tinder_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tindetitem',
            name='unit',
            field=models.CharField(default='piece', max_length=25),
        ),
    ]
