# Generated by Django 4.2 on 2025-11-12 15:13

import datetime
from django.db import migrations, models
import tinder.models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0005_alter_tinder_created_at_alter_tinder_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 12, 15, 13, 32, 813273, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tinderfiles',
            name='files',
            field=models.FileField(upload_to=tinder.models.tender_file_upload_path),
        ),
    ]
