# Generated by Django 4.2 on 2025-11-26 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0005_alter_tinder_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tindetitem',
            old_name='statement',
            new_name='statment',
        ),
        migrations.AlterField(
            model_name='tinder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 26, 15, 51, 54, 218824, tzinfo=datetime.timezone.utc)),
        ),
    ]
