# Generated by Django 4.2 on 2025-11-13 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0006_alter_tinder_created_at_alter_tinderfiles_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tindetitem',
            name='category',
        ),
        migrations.AddField(
            model_name='tindetitem',
            name='unit',
            field=models.CharField(default='pice', max_length=25),
        ),
        migrations.AlterField(
            model_name='tinder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 13, 7, 22, 6, 885096, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tinder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('CANCEL', 'CANCEL'), ('AWARED', 'AWARED')], max_length=75),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
