# Generated by Django 4.2 on 2025-11-27 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0006_rename_statement_tindetitem_statment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 27, 7, 0, 4, 373623, tzinfo=datetime.timezone.utc)),
        ),
    ]
