# Generated by Django 4.2 on 2025-11-13 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0007_remove_tindetitem_category_tindetitem_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 13, 7, 24, 52, 54610, tzinfo=datetime.timezone.utc)),
        ),
    ]
