# Generated by Django 4.2 on 2025-11-15 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0008_alter_tinder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 15, 10, 36, 32, 147614, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tindetitem',
            name='code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
