# Generated by Django 4.2 on 2025-11-27 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0009_alter_tinder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tindetitem',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tinder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 27, 9, 50, 12, 77816, tzinfo=datetime.timezone.utc)),
        ),
    ]
