# Generated by Django 4.2 on 2025-11-16 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0009_alter_tinder_created_at_alter_tindetitem_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinder',
            name='close_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tinder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 16, 12, 31, 40, 712254, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tinder',
            name='open_date',
            field=models.DateField(),
        ),
    ]
