# Generated by Django 4.2 on 2025-11-16 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0010_alter_tinder_close_date_alter_tinder_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 16, 16, 4, 6, 268452, tzinfo=datetime.timezone.utc)),
        ),
    ]
