# Generated by Django 4.2 on 2025-11-29 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0010_tindetitem_total_alter_tinder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 29, 7, 10, 47, 820075, tzinfo=datetime.timezone.utc)),
        ),
    ]
