# Generated by Django 4.2 on 2025-11-17 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0011_alter_tinder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 17, 9, 15, 27, 33337, tzinfo=datetime.timezone.utc)),
        ),
    ]
