# Generated by Django 4.2 on 2025-11-29 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0011_alter_tinder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 29, 8, 0, 23, 584147, tzinfo=datetime.timezone.utc)),
        ),
    ]
