# Generated by Django 4.2 on 2025-11-30 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0012_alter_tinder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 8, 9, 41, 727528, tzinfo=datetime.timezone.utc)),
        ),
    ]
