# Generated by Django 4.2 on 2025-11-17 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0012_alter_tinder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 17, 14, 47, 7, 803266, tzinfo=datetime.timezone.utc)),
        ),
    ]
