# Generated by Django 4.2 on 2025-12-02 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0020_alter_tinder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 2, 7, 10, 1, 938020, tzinfo=datetime.timezone.utc)),
        ),
    ]
