# Generated by Django 4.2 on 2025-12-04 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0021_alter_tinder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 4, 7, 44, 41, 497601, tzinfo=datetime.timezone.utc)),
        ),
    ]
