# Generated by Django 4.2 on 2025-12-07 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0022_alter_tinder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 7, 7, 18, 30, 163747, tzinfo=datetime.timezone.utc)),
        ),
    ]
