# Generated by Django 4.2 on 2025-11-25 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('CASH', 'نقدي'), ('CHEQUE', 'شيكات')], max_length=75)),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('details', models.TextField(max_length=1500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edit_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transaction', models.DateField()),
                ('no', models.IntegerField()),
                ('inbox', models.FloatField(blank=True, null=True)),
                ('absentminded', models.FloatField(blank=True, null=True)),
                ('details', models.TextField(blank=True, max_length=1500, null=True)),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_cashbox', to='accounting.cashbox')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_category', to='accounting.category')),
            ],
        ),
    ]
