# Generated by Django 4.2 on 2025-11-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='type',
            field=models.CharField(choices=[('CASH', 'نقدي'), ('CHEQUE', 'شيكات')], max_length=75),
        ),
    ]
