# Generated by Django 4.2 on 2025-11-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_cashbox_is_active_alter_cashbox_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='details',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
