# Generated by Django 4.2 on 2025-11-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_cashtransaction_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='date_transaction',
            field=models.DateField(),
        ),
    ]
